
services:
  postgres:
    image: postgres:16
    container_name: aula-node-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: aula_node_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   

volumes:
  postgres_data:
 
